[logger]
Filename = "./logs/chainFinder.log"
Level = "debug"
Compress = false
MaxSize = 10
MaxAge = 7
MaxBackups = 512
Named = "[TYCHE]"

[redis]
Domain = "data:chainFinder127"
MaxIdle = 8
MaxActive = 0
IdleTimeout = 0
URI = "redis://:@127.0.0.1:6379/3"
Address = "192.168.101.12:3306"
Password ="123456"
Username = "root"
Database = "chainfindata"

[chainFinder]
Listen = "0.0.0.0:18072"
ReadTimeout = 15
WriteTimeout = 15
MaxHeaderBytes = 8192

# HTTPS
EnableTLS = false
CertFile = "./pem/tyche.com.crt"
keyFile = "./pem/tyche.com.key"

# 回调
ErrorURI = "http://127.0.0.1:8081/event/error"
SucceedURI = "http://127.0.0.1:8081/event/succeed"
FailedURI = "http://127.0.0.1:8081/event/failed"
Callback = "http://127.0.0.1:8071/tyche/api/call"
ContractCreationTime = "http://127.0.0.1:8071/tyche/api/wallet/contractTxCount"
ContractTxCount = "http://127.0.0.1:8071/tyche/api/wallet/contractTxCount"
GetGasPrice = "http://127.0.0.1:8071/tyche/api/wallet/GetGasPrice"
BalanceAt = "http://127.0.0.1:8071/tyche/api/wallet/balance_at"
CompareBytecodeAndSourceCode = "http://127.0.0.1:8071/tyche/api/wallet/CompareBytecodeAndSourceCode"


# 链地址的前缀
PrefixChain ="F"

# 并发控制
ErrorNumberOfConcurrent = 4
FailedNumberOfConcurrent= 4
PendingNumberOfConcurrent = 16
SentNumberOfConcurrent = 1
SucceedNumberOfConcurrent= 4

# GasPrice
EstimatorJS = "./js/gasprice.js"
GasPriceUpdateInterval = 5

# Nonce
NonceCheckInterval = 3
NonceKeepalive = 60
MaxBumpingGasTimes = 10

# 重试
PendingRetryInterval = 1
SentRetryInterval = 1
RedisRetryInterval = 3
NetworkRetryInterval = 5
WaitMinedRetryInterval = 10
CallbackRetryInterval = 15

[backend]
#Addr = "http://127.0.0.1:8545"
Addr = "https://rpc.novaichain.com"
DefaultGasLimit = 5500000
TransactionsPerSecond = 20


[[backend.headers]]
Key = "x-api-key"
Value = "6ef17cd9d9cc4d3b9e9d1945742f22d2"